### ISSUE TITLE
Update template README to use terra-ui Features Link

### ISSUE THREAD

**Issue by emilyrohrbough** [cerner/generator-terra-module#113]
# Bug Report

## Description
Update README links to point to terra-ui:

https://engineering.cerner.com/terra-ui/#/getting-started/terra-ui/features

Currently links are broken and attempt to create a new wiki page in terra-core

**Comment by bjankord** [comment]
Resolved in https://github.com/cerner/generator-terra-module/commit/b96f43d6fe87e7a37a8e6a6999aa4cbd05aeecee
