### ISSUE TITLE
Remove terra-base peer dependency from template

### ISSUE THREAD

**Issue by yuderekyu** [cerner/generator-terra-module#118]
# Feature Request
`terra-base` should not be peer dependency of components anymore [[1](https://github.com/cerner/terra-core/issues/2291)]. Lets remove `terra-base` from the component template package.json.

**Comment by bjankord** [comment]
Need to remove these lines:
* https://github.com/cerner/generator-terra-module/blob/2d313e36b6de3309d0f786f2fe1fa760468b660f/generators/app/templates/package.json#L26
* https://github.com/cerner/generator-terra-module/blob/5d2a8b99d9f825861417172f9de6540b20ae7a1a/generators/app/templates/src/projectName.jsx#L4
