### ISSUE TITLE
Add wdio.conf.js to package template

### ISSUE THREAD

**Issue by bjankord** [cerner/generator-terra-module#137]
With the update to terra-dev-site v6, packages are expected to have a `wdio.conf.js` file in them if they are being generated for one of the monorepos. You can view one of these files here: https://github.com/cerner/terra-core/blob/master/packages/terra-button/wdio.conf.js

**Comment by yuderekyu** [comment]
has been added https://github.com/cerner/generator-terra-module/blob/master/generators/app/templates/wdio.conf.js
