### ISSUE TITLE
Remove react as a dependency

### ISSUE THREAD

**Issue by Matt-Butler** [cerner/generator-terra-module#34]
Having react as a dependency can cause multiple versions of react to be installed. Instead, it should just be a peerDependency.

This is what cloudflare-ui does: https://github.com/cloudflare/cf-ui/blob/master/packages/cf-builder-table/package.json#L20

Update this code:
https://github.com/cerner/generator-terra-module/blob/master/generators/app/templates/package.json#L33

**Comment by emilyrohrbough** [comment]
This change was made [here](https://github.com/cerner/generator-terra-module/pull/40/files#diff-ecc2faf184f0e6bdac0cdbdefff61b13L34) in https://github.com/cerner/generator-terra-module/pull/40
