### ISSUE TITLE
Lint errors in Jest test file due to global Enzyme functions

### ISSUE THREAD

**Issue by tbiethman** [cerner/generator-terra-module#6]
Now that we're globally defining the shallow, render, and mount functions from Enzyme in jestsetup.js, the test file itself has lint errors due do missing function imports for them.

This isn't a build issue since we don't lint our test files. But we might want to? As it is, it's just annoying to look at.

#### Generator Version
As of 95c08ffcaf752427a2caf88a2e216aa79f7656bd

#### Node Version
v6.9.4

### Expected Outcomes
- Either we don't import them globally, or we include eslint ignores to hide the issue. Personally, I'd prefer the former if we're going to start linting our test files.

**Comment by ryanthemanuel** [comment]
+1 to listing our test files.  Tests are code too and need to be maintainable.

**Comment by Matt-Butler** [comment]
+1 

Eslint does not have an environment for enzyme. 
http://eslint.org/docs/user-guide/configuring#specifying-environments

1) We could add this to .eslintrc
```
  "globals": {
    "shallow": true,
    "render": true,
    "mount": true
  }
```
2) We could explicitly import those methods and no longer have them as global.

**Comment by bjankord** [comment]
+1 to linting test files. @Matt-Butler option 1 or 2 both seem reasonable to me.

**Comment by ryanthemanuel** [comment]
I'm fine with either option as well.  I've noticed a few other places that we're not linting either so I thought i'd get opinions about them:  .storybook/, stories/  I'm of the mind to lint everything, but wanted to hear what others thought.

**Comment by mjhenkes** [comment]
+1 to lint all the things

**Comment by bjankord** [comment]
Consensus landed on is to go with option 1 @Matt-Butler suggested.

**Comment by windse7en** [comment]
Close this issue. It's already fixed.
