### ISSUE TITLE
Change site package name for Framework

### ISSUE THREAD

**Issue by yuderekyu** [cerner/generator-terra-module#78]
### Description of Issue
`terra-framework` needs packages generated with no framework prefix, #76 . **But**, the existing framework site package is called `terra-framework-site`. Currently, the generator just re-uses the repo name which is set to `terra`. This results in a new `terra-site` package being generated, instead of generating examples within `terra-site-framework`.

**Comment by emilyrohrbough** [comment]
Resolved in #25.
