### ISSUE TITLE
Update package.json Template to Use React v16 Dependencies

### ISSUE THREAD

**Issue by dev-cprice** [cerner/generator-terra-module#85]
### Description of Issue
In the [template package.json file](https://github.com/cerner/generator-terra-module/blob/master/generators/app/templates/package.json#L23-L35), React v15 and React v15 `terra-core` components are used as dependencies. These should be updated to their React 16 versions.

<img width="1067" alt="screen shot 2018-03-01 at 10 20 22 am" src="https://user-images.githubusercontent.com/34115417/36856840-a154a0d0-1d3c-11e8-8a8e-f38d012bfd86.png">

#### Generator Version
1.6.0

#### Node Version
8.9.2

### Steps to Reproduce the Issue
1. [Scaffold a new component](https://github.com/cerner/generator-terra-module#getting-started)
1. Look at new component package.json dependencies

### Expected Outcomes
- Dependency React version should be v16
- Dependency Terra components should be React v16 versions

**Comment by mjhenkes** [comment]
Released with the 1.7.0 version of the generator
